
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { AuthProvider } from "@/context/AuthContext";

import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Campus Connect",
  description: "Generated by create next app",
};


import { QueryClient, QueryClientProvider } from "@tanstack/react-query";






export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <AuthProvider>
      <body className={inter.className}>
        <Navbar/>
       
        <main>
       
        {children}
       
        </main>
       
        <Toaster />
        </body>
      </AuthProvider>
    </html>

  );
}
